global:
  # How frequently to scrape targets
  scrape_interval:  30s

scrape_configs:
  - job_name: 'smarthome'
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token: 'TOKEN'
    scheme: http
    static_configs:
      - targets:
        - homeassistant:8123